[build]
  command = "npm run build"
  publish = ".next"
  environment = { NODE_VERSION = "20" }

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  # Ensure Next.js build optimizations
  NEXT_TELEMETRY_DISABLED = "1"
  
# Handle client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = { Role = ["user"] }
