export const coreAutoTasks = [
  // RELATIONSHIP (20)
  { id: 'rel_001', title: 'Ask how her day was', detail: 'Before launching into yours', category: 'relationship', simplicity: 'low' },
  { id: 'rel_002', title: 'Put your phone away at dinner', detail: 'Just for 20 minutes', category: 'relationship', simplicity: 'low' },
  { id: 'rel_003', title: 'Text her something appreciative', detail: 'Make it specific', category: 'relationship', simplicity: 'low' },
  { id: 'rel_004', title: 'Clean up after dinner', detail: 'Without being asked', category: 'relationship', simplicity: 'medium' },
  { id: 'rel_005', title: 'Plan something together', detail: 'Even if it’s small', category: 'relationship', simplicity: 'medium' },
  { id: 'rel_006', title: 'Offer her 30 minutes alone', detail: 'Handle baby solo', category: 'relationship', simplicity: 'medium' },
  { id: 'rel_007', title: 'Say thank you for something', detail: 'Not sarcastic', category: 'relationship', simplicity: 'low' },
  { id: 'rel_008', title: 'Bring her a snack or drink', detail: 'Small gesture, big impact', category: 'relationship', simplicity: 'low' },
  { id: 'rel_009', title: 'Sit and talk for 5 mins', detail: 'No screens', category: 'relationship', simplicity: 'low' },
  { id: 'rel_010', title: 'Give her a real compliment', detail: 'Something meaningful', category: 'relationship', simplicity: 'low' },
  { id: 'rel_011', title: 'Handle bedtime solo', detail: 'Let her rest', category: 'relationship', simplicity: 'high' },
  { id: 'rel_012', title: 'Prep her morning coffee', detail: 'Exactly how she likes it', category: 'relationship', simplicity: 'low' },
  { id: 'rel_013', title: 'Schedule a date night', detail: 'Even if it’s just takeout', category: 'relationship', simplicity: 'medium' },
  { id: 'rel_014', title: 'Tell her one thing she’s great at', detail: 'From the heart', category: 'relationship', simplicity: 'low' },
  { id: 'rel_015', title: 'Do something on her mental list', detail: 'Without asking', category: 'relationship', simplicity: 'medium' },
  { id: 'rel_016', title: 'Surprise her with a break', detail: 'No strings', category: 'relationship', simplicity: 'medium' },
  { id: 'rel_017', title: 'Rub her back or shoulders', detail: '2–3 minutes', category: 'relationship', simplicity: 'low' },
  { id: 'rel_018', title: 'Check in about her stress level', detail: 'Just ask and listen', category: 'relationship', simplicity: 'low' },
  { id: 'rel_019', title: 'Share something funny from your day', detail: 'Laughter helps', category: 'relationship', simplicity: 'low' },
  { id: 'rel_020', title: 'Take over baby duty without asking', detail: 'She’ll notice', category: 'relationship', simplicity: 'medium' },

  // BABY (20)
  { id: 'baby_001', title: 'Wash bottles/pump parts', detail: 'For tomorrow', category: 'baby', simplicity: 'medium' },
  { id: 'baby_002', title: 'Refill wipes and diapers', detail: 'Check every bag and room', category: 'baby', simplicity: 'medium' },
  { id: 'baby_003', title: 'Label and prep daycare bottles', detail: 'Tonight not tomorrow', category: 'baby', simplicity: 'medium' },
  { id: 'baby_004', title: 'Wipe down high chair or toys', detail: 'Quick clean', category: 'baby', simplicity: 'medium' },
  { id: 'baby_005', title: 'Trim baby’s nails', detail: 'Best when they’re sleepy', category: 'baby', simplicity: 'medium' },
  { id: 'baby_006', title: 'Restock medicine cabinet', detail: 'Check infant Tylenol, etc.', category: 'baby', simplicity: 'medium' },
  { id: 'baby_007', title: 'Pack a spare outfit', detail: 'For diaper bag or car', category: 'baby', simplicity: 'low' },
  { id: 'baby_008', title: 'Check next pediatrician visit', detail: 'Schedule if needed', category: 'baby', simplicity: 'low' },
  { id: 'baby_009', title: 'Read a book to baby', detail: 'Same one is fine', category: 'baby', simplicity: 'low' },
  { id: 'baby_010', title: 'Sanitize pacifiers or teethers', detail: 'Boil or rinse', category: 'baby', simplicity: 'medium' },
  { id: 'baby_011', title: 'Update daycare info', detail: 'New nap, food, meds?', category: 'baby', simplicity: 'low' },
  { id: 'baby_012', title: 'Take baby outside', detail: '5–10 min fresh air', category: 'baby', simplicity: 'medium' },
  { id: 'baby_013', title: 'Start bedtime routine early', detail: 'Avoid the crash', category: 'baby', simplicity: 'medium' },
  { id: 'baby_014', title: 'Disinfect changing area', detail: 'Quick wipe down', category: 'baby', simplicity: 'medium' },
  { id: 'baby_015', title: 'Prep next size clothes', detail: 'Baby grows fast', category: 'baby', simplicity: 'high' },
  { id: 'baby_016', title: 'Take photos or videos', detail: 'Memory time', category: 'baby', simplicity: 'low' },
  { id: 'baby_017', title: 'Organize toys', detail: 'Clear a space', category: 'baby', simplicity: 'medium' },
  { id: 'baby_018', title: 'Make a backup daycare kit', detail: 'Leave in car or bag', category: 'baby', simplicity: 'high' },
  { id: 'baby_019', title: 'Make a batch of puree/snacks', detail: 'Freeze or store', category: 'baby', simplicity: 'high' },
  { id: 'baby_020', title: 'Rotate toys or books', detail: 'Freshens engagement', category: 'baby', simplicity: 'medium' },

  // HOUSEHOLD (20)
  { id: 'house_001', title: 'Start the dishwasher', detail: 'Before bed', category: 'household', simplicity: 'low' },
  { id: 'house_002', title: 'Wipe kitchen counters', detail: '2-minute reset', category: 'household', simplicity: 'low' },
  { id: 'house_003', title: 'Take out the trash', detail: 'Check all bins', category: 'household', simplicity: 'low' },
  { id: 'house_004', title: 'Change the bed sheets', detail: 'Fresh start', category: 'household', simplicity: 'high' },
  { id: 'house_005', title: 'Run a load of laundry', detail: 'Just start it', category: 'household', simplicity: 'medium' },
  { id: 'house_006', title: 'Tidy main living area', detail: '5 minute reset', category: 'household', simplicity: 'medium' },
  { id: 'house_007', title: 'Wipe down bathroom sink', detail: 'Quick clean', category: 'household', simplicity: 'low' },
  { id: 'house_008', title: 'Restock paper goods', detail: 'Toilet paper, tissues', category: 'household', simplicity: 'medium' },
  { id: 'house_009', title: 'Check grocery essentials', detail: 'Add to list', category: 'household', simplicity: 'low' },
  { id: 'house_010', title: 'Empty diaper trash', detail: 'The smell adds up', category: 'household', simplicity: 'low' },
  { id: 'house_011', title: 'Clean out the fridge', detail: 'Old leftovers out', category: 'household', simplicity: 'high' },
  { id: 'house_012', title: 'Set up coffee for morning', detail: 'Future you thanks you', category: 'household', simplicity: 'low' },
  { id: 'house_013', title: 'Clean microwave', detail: 'Fast and satisfying', category: 'household', simplicity: 'medium' },
  { id: 'house_014', title: 'Declutter entryway', detail: 'Shoes, bags, mail', category: 'household', simplicity: 'medium' },
  { id: 'house_015', title: 'Water the plants', detail: 'They’re part of the home too', category: 'household', simplicity: 'low' },
  { id: 'house_016', title: 'Sweep high-traffic zone', detail: 'Kitchen or hallway', category: 'household', simplicity: 'medium' },
  { id: 'house_017', title: 'Vacuum for 5 minutes', detail: 'Start somewhere', category: 'household', simplicity: 'medium' },
  { id: 'house_018', title: 'Wipe remote controls/handles', detail: 'Germ hotspots', category: 'household', simplicity: 'low' },
  { id: 'house_019', title: 'Check and sort mail pile', detail: 'Recycle junk now', category: 'household', simplicity: 'medium' },
  { id: 'house_020', title: 'Organize one drawer', detail: 'Pick your messiest', category: 'household', simplicity: 'medium' },

  // SELF (15)
  { id: 'self_001', title: 'Drink a full glass of water', detail: 'Right now', category: 'self', simplicity: 'low' },
  { id: 'self_002', title: 'Take 3 deep breaths', detail: 'Reset your brain', category: 'self', simplicity: 'low' },
  { id: 'self_003', title: 'Stretch for 5 minutes', detail: 'Back and neck', category: 'self', simplicity: 'low' },
  { id: 'self_004', title: 'Text a friend', detail: 'Just to check in', category: 'self', simplicity: 'low' },
  { id: 'self_005', title: 'Go for a walk', detail: '10 minutes is enough', category: 'self', simplicity: 'medium' },
  { id: 'self_006', title: 'Take vitamins or meds', detail: 'Stay consistent', category: 'self', simplicity: 'low' },
  { id: 'self_007', title: 'Journal a quick thought', detail: '1 sentence is enough', category: 'self', simplicity: 'low' },
  { id: 'self_008', title: 'Plan something fun', detail: 'Something to look forward to', category: 'self', simplicity: 'medium' },
  { id: 'self_009', title: 'Queue up a playlist you love', detail: 'Music resets your vibe', category: 'self', simplicity: 'low' },
  { id: 'self_010', title: 'Plan tomorrow’s meals', detail: 'No pressure, just glance ahead', category: 'self', simplicity: 'medium' },
  { id: 'self_011', title: 'Take a screen break', detail: '5 minutes away from devices', category: 'self', simplicity: 'low' },
  { id: 'self_012', title: 'Check your posture', detail: 'Fix it for 1 minute', category: 'self', simplicity: 'low' },
  { id: 'self_013', title: 'Plan 1 self-care thing this week', detail: 'Lock it in', category: 'self', simplicity: 'medium' },
  { id: 'self_014', title: 'Read 2 pages of a book', detail: 'Fiction or fun only', category: 'self', simplicity: 'low' },
  { id: 'self_015', title: 'Schedule a haircut', detail: 'Finally', category: 'self', simplicity: 'medium' },
];